apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litmus

resources:
  - namespace.yaml
  - chaoshub.yaml
  - workflows/validator-chaos.yaml
  - workflows/provider-chaos.yaml

commonLabels:
  app.kubernetes.io/part-of: virtengine
  app.kubernetes.io/component: chaos-testing
