apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chaos-testing

resources:
  - namespace.yaml
  - rbac.yaml
  - network-chaos.yaml
  - pod-chaos.yaml
  - stress-chaos.yaml
  - time-chaos.yaml

commonLabels:
  app.kubernetes.io/part-of: virtengine
  app.kubernetes.io/component: chaos-testing
