apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    app.kubernetes.io/part-of: virtengine
    app.kubernetes.io/component: chaos-testing
    chaos-mesh.org/injection: enabled
