apiVersion: v2
name: slurm-cluster
description: VirtEngine SLURM HPC cluster deployment on Kubernetes
type: application
version: 0.1.0
appVersion: "23.02.7"

keywords:
  - slurm
  - hpc
  - high-performance-computing
  - kubernetes
  - virtengine

home: https://github.com/virtengine/virtengine
sources:
  - https://github.com/virtengine/virtengine

maintainers:
  - name: VirtEngine Team
    email: support@virtengine.dev

annotations:
  virtengine.com/component: hpc
  virtengine.com/module: slurm
