apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-mesh-s2s
  namespace: virtengine
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - virtengine
              - istio-system
