apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: virtengine-default
  namespace: virtengine
spec:
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
