{{/*
VE-502: ServiceAccount for SLURM cluster
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-cluster.serviceAccountName" . }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
